line-length = 120

[lint]
select = ["ALL"]
extend-ignore = [
    "D100",    # docstring in module
    "D104",    # docstring in package
    "D105",    # docstring in magic method
    "D101",    # docstring in class
    "D107",    # docstring in __init__
    "ERA001",  # no comments
    "FIX002",  # no TODOs
    "TD003",   # todos need links
    "TD002",   # todos need authors
    "FBT",     # boolean defaults
    "SLF001",  # accessing privates (TODO: REMOVE)
    "E501",    # line too long
    "PLC0414", # redundant reexport
    "S105",    # hardcoded token
    "A005",    # module builtin shadow (TODO: REMOVE)
    "B019",    # cache can lead to mem leak (TODO: REMOVE)
    "PLR0912", # too many branches (TODO: REMOVE)
    "C901",    # too complex (TODO: REMOVE)
]

# preview = true

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.pydocstyle]
convention = "google"
ignore-var-parameters = true

[lint.extend-per-file-ignores]
"tests/*" = [
    "S101",    # no assets
    "D",
    "ANN",     # require annotations
    "PLR2004",
    "INP001",
    "PLR0913", # max 5 args for functions
]
