name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
    permissions:
      contents: write
      pull-requests: write

  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == github.repository_owner
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto-approved PR by repository owner"