name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
    permissions:
      contents: write
      pull-requests: write
